# Generated by Django 4.2.11 on 2024-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, verbose_name='Node ID')),
                ('organization_uuid', models.UUIDField(unique=True, verbose_name='Organization UUID')),
                ('controller_token', models.CharField(max_length=50, verbose_name='Token')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('license_string', models.TextField(blank=True, help_text='Copy this to site, and input in License Code', null=True, verbose_name='License Code')),
                ('license_site', models.TextField(blank=True, help_text='Copy this to site, and input in Lisense Key', null=True, verbose_name='Site License')),
                ('license_server', models.TextField(blank=True, help_text='Keep this in License Server', null=True, verbose_name='Server License')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'licenses',
            },
        ),
    ]
