# Generated by Django 4.2.11 on 2024-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_licenses_created_at_licenses_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenses',
            name='is_block_rule',
            field=models.BooleanField(default=True, verbose_name='Block at Expired'),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='organization_uuid',
            field=models.UUIDField(unique=True, verbose_name='UUID'),
        ),
    ]
